# Generated by Django 4.1.2 on 2022-10-06 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='basket',
            name='status',
            field=models.IntegerField(choices=[(1, 'W trakcie przygotowania'), (2, 'Oczekujące na płatność'), (3, 'Zrealizowane')]),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='payment_method',
            field=models.IntegerField(choices=[(1, 'Za pobraniem'), (2, 'Odbiór osobisty'), (3, 'Przelew')]),
        ),
    ]
