# Generated by Django 4.1.2 on 2022-10-06 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_users_user_alter_basket_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='delivery_method',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.delivery'),
        ),
    ]
