# Generated by Django 4.1.2 on 2022-10-06 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_basket_delivery_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='name',
        ),
    ]
