# Generated by Django 4.1.2 on 2022-10-07 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_delivery_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='user',
            new_name='my_user',
        ),
    ]
