# Generated by Django 4.1.2 on 2022-10-07 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_user_basket_my_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='delivery_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.delivery'),
        ),
    ]
