# Generated by Django 4.1.2 on 2022-10-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_basket_delivery_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='payment_method',
            field=models.IntegerField(choices=[(1, 'Za pobraniem'), (2, 'Przelew')]),
        ),
    ]
